/* 英语学习工作台 · 资料数据：六级核心词表 / 口语话题与表达 / 资源链接导航 */

/* ================= 六级核心词（约200个高频词） ================= */
const WORDS = [
  {w:'abandon', m:'放弃；抛弃', p:'v'},
  {w:'absorb', m:'吸收；吸引', p:'v'},
  {w:'accelerate', m:'加速', p:'v'},
  {w:'accommodate', m:'容纳；为…提供住宿', p:'v'},
  {w:'accumulate', m:'积累', p:'v'},
  {w:'acknowledge', m:'承认；致谢', p:'v'},
  {w:'acquire', m:'获得', p:'v'},
  {w:'adapt', m:'适应；改编', p:'v'},
  {w:'advocate', m:'提倡', p:'v'},
  {w:'allocate', m:'分配', p:'v'},
  {w:'alter', m:'改变', p:'v'},
  {w:'anticipate', m:'预期', p:'v'},
  {w:'appreciate', m:'欣赏；感激', p:'v'},
  {w:'assess', m:'评估', p:'v'},
  {w:'assume', m:'假定；承担', p:'v'},
  {w:'attain', m:'达到；获得', p:'v'},
  {w:'attribute', m:'把…归因于', p:'v'},
  {w:'boost', m:'促进；提升', p:'v'},
  {w:'cease', m:'停止', p:'v'},
  {w:'clarify', m:'澄清', p:'v'},
  {w:'collapse', m:'倒塌；崩溃', p:'v'},
  {w:'compensate', m:'补偿；弥补', p:'v'},
  {w:'comply', m:'遵从', p:'v'},
  {w:'conceive', m:'构想', p:'v'},
  {w:'confirm', m:'确认', p:'v'},
  {w:'confront', m:'面对；对抗', p:'v'},
  {w:'conserve', m:'保护；节约', p:'v'},
  {w:'consolidate', m:'巩固', p:'v'},
  {w:'constitute', m:'构成', p:'v'},
  {w:'contribute', m:'贡献；促成', p:'v'},
  {w:'convey', m:'传达', p:'v'},
  {w:'convince', m:'说服', p:'v'},
  {w:'cooperate', m:'合作', p:'v'},
  {w:'cultivate', m:'培养；耕种', p:'v'},
  {w:'decline', m:'下降；婉拒', p:'v'},
  {w:'demonstrate', m:'证明；演示', p:'v'},
  {w:'deny', m:'否认', p:'v'},
  {w:'deprive', m:'剥夺', p:'v'},
  {w:'derive', m:'源于；取得', p:'v'},
  {w:'diminish', m:'减少；削弱', p:'v'},
  {w:'discard', m:'丢弃', p:'v'},
  {w:'disclose', m:'揭露；透露', p:'v'},
  {w:'discourage', m:'劝阻', p:'v'},
  {w:'discriminate', m:'歧视；区分', p:'v'},
  {w:'dismiss', m:'驳回；解雇', p:'v'},
  {w:'dispose', m:'处理；处置', p:'v'},
  {w:'distort', m:'歪曲', p:'v'},
  {w:'dominate', m:'主导', p:'v'},
  {w:'elaborate', m:'详述', p:'v'},
  {w:'eliminate', m:'消除；淘汰', p:'v'},
  {w:'emphasize', m:'强调', p:'v'},
  {w:'encounter', m:'遭遇', p:'v'},
  {w:'enhance', m:'增强', p:'v'},
  {w:'evaluate', m:'评价', p:'v'},
  {w:'exaggerate', m:'夸大', p:'v'},
  {w:'exceed', m:'超过', p:'v'},
  {w:'expose', m:'暴露；揭露', p:'v'},
  {w:'facilitate', m:'促进；使便利', p:'v'},
  {w:'fluctuate', m:'波动', p:'v'},
  {w:'forecast', m:'预测', p:'v'},
  {w:'formulate', m:'制定；阐述', p:'v'},
  {w:'foster', m:'培养；促进', p:'v'},
  {w:'fulfill', m:'履行；实现', p:'v'},
  {w:'generate', m:'产生', p:'v'},
  {w:'guarantee', m:'保证', p:'v'},
  {w:'identify', m:'识别；认同', p:'v'},
  {w:'implement', m:'实施', p:'v'},
  {w:'impose', m:'强加；征收', p:'v'},
  {w:'incorporate', m:'纳入；包含', p:'v'},
  {w:'induce', m:'诱发', p:'v'},
  {w:'infer', m:'推断', p:'v'},
  {w:'inhibit', m:'抑制', p:'v'},
  {w:'inspire', m:'鼓舞；启发', p:'v'},
  {w:'integrate', m:'整合', p:'v'},
  {w:'interfere', m:'干涉', p:'v'},
  {w:'interpret', m:'解释；口译', p:'v'},
  {w:'intervene', m:'干预', p:'v'},
  {w:'investigate', m:'调查', p:'v'},
  {w:'isolate', m:'隔离', p:'v'},
  {w:'justify', m:'证明…有理', p:'v'},
  {w:'maintain', m:'维持；保养', p:'v'},
  {w:'manipulate', m:'操纵', p:'v'},
  {w:'maximize', m:'最大化', p:'v'},
  {w:'merge', m:'合并', p:'v'},
  {w:'minimize', m:'最小化', p:'v'},
  {w:'modify', m:'修改', p:'v'},
  {w:'motivate', m:'激励', p:'v'},
  {w:'negotiate', m:'谈判', p:'v'},
  {w:'occupy', m:'占据；占用', p:'v'},
  {w:'offset', m:'抵消', p:'v'},
  {w:'overcome', m:'克服', p:'v'},
  {w:'participate', m:'参与', p:'v'},
  {w:'perceive', m:'感知；认为', p:'v'},
  {w:'persist', m:'坚持；持续', p:'v'},
  {w:'persuade', m:'说服', p:'v'},
  {w:'pose', m:'造成（威胁等）', p:'v'},
  {w:'precede', m:'先于', p:'v'},
  {w:'predict', m:'预测', p:'v'},
  {w:'prevail', m:'盛行；获胜', p:'v'},
  {w:'proceed', m:'继续进行', p:'v'},
  {w:'promote', m:'促进；晋升', p:'v'},
  {w:'prompt', m:'促使；激起', p:'v'},
  {w:'prosper', m:'繁荣', p:'v'},
  {w:'pursue', m:'追求；从事', p:'v'},
  {w:'reconcile', m:'调和；和解', p:'v'},
  {w:'refine', m:'精炼；改进', p:'v'},
  {w:'reinforce', m:'强化', p:'v'},
  {w:'reject', m:'拒绝', p:'v'},
  {w:'release', m:'释放；发布', p:'v'},
  {w:'relieve', m:'减轻', p:'v'},
  {w:'render', m:'使得；提供', p:'v'},
  {w:'reproduce', m:'复制；繁殖', p:'v'},
  {w:'resemble', m:'类似', p:'v'},
  {w:'restore', m:'恢复', p:'v'},
  {w:'restrain', m:'抑制', p:'v'},
  {w:'retain', m:'保留', p:'v'},
  {w:'reveal', m:'揭示', p:'v'},
  {w:'revive', m:'复兴；复苏', p:'v'},
  {w:'safeguard', m:'保护', p:'v'},
  {w:'scatter', m:'散落；驱散', p:'v'},
  {w:'seize', m:'抓住', p:'v'},
  {w:'simulate', m:'模拟', p:'v'},
  {w:'speculate', m:'推测', p:'v'},
  {w:'stimulate', m:'刺激', p:'v'},
  {w:'strive', m:'努力', p:'v'},
  {w:'substitute', m:'替代', p:'v'},
  {w:'suppress', m:'镇压；抑制', p:'v'},
  {w:'surpass', m:'超越', p:'v'},
  {w:'sustain', m:'维持；支撑', p:'v'},
  {w:'tackle', m:'处理', p:'v'},
  {w:'tempt', m:'诱惑', p:'v'},
  {w:'terminate', m:'终止', p:'v'},
  {w:'thrive', m:'兴旺', p:'v'},
  {w:'tolerate', m:'容忍', p:'v'},
  {w:'transfer', m:'转移', p:'v'},
  {w:'transform', m:'转变', p:'v'},
  {w:'trigger', m:'引发', p:'v'},
  {w:'undergo', m:'经历', p:'v'},
  {w:'undermine', m:'削弱', p:'v'},
  {w:'undertake', m:'承担；着手', p:'v'},
  {w:'utilize', m:'利用', p:'v'},
  {w:'verify', m:'核实', p:'v'},
  {w:'violate', m:'违反', p:'v'},
  {w:'withdraw', m:'撤回；退出', p:'v'},
  {w:'abundance', m:'丰富；充裕', p:'n'},
  {w:'access', m:'进入；使用权', p:'n'},
  {w:'achievement', m:'成就', p:'n'},
  {w:'advantage', m:'优势', p:'n'},
  {w:'alternative', m:'替代方案', p:'n'},
  {w:'ambition', m:'抱负', p:'n'},
  {w:'analogy', m:'类比', p:'n'},
  {w:'appeal', m:'吸引力；呼吁', p:'n'},
  {w:'approval', m:'批准；赞成', p:'n'},
  {w:'asset', m:'资产；宝贵的人/物', p:'n'},
  {w:'assumption', m:'假定', p:'n'},
  {w:'authority', m:'权威；当局', p:'n'},
  {w:'barrier', m:'障碍', p:'n'},
  {w:'budget', m:'预算', p:'n'},
  {w:'capacity', m:'能力；容量', p:'n'},
  {w:'circumstance', m:'情况；环境', p:'n'},
  {w:'commitment', m:'承诺；投入', p:'n'},
  {w:'commodity', m:'商品', p:'n'},
  {w:'community', m:'社区；群体', p:'n'},
  {w:'competence', m:'能力', p:'n'},
  {w:'component', m:'组成部分', p:'n'},
  {w:'compromise', m:'妥协', p:'n'},
  {w:'concept', m:'概念', p:'n'},
  {w:'consequence', m:'后果', p:'n'},
  {w:'conservation', m:'保护；节约', p:'n'},
  {w:'constraint', m:'限制', p:'n'},
  {w:'consumption', m:'消费；消耗', p:'n'},
  {w:'controversy', m:'争议', p:'n'},
  {w:'conviction', m:'信念；定罪', p:'n'},
  {w:'criterion', m:'（判断）标准', p:'n'},
  {w:'deficiency', m:'缺乏；不足', p:'n'},
  {w:'deficit', m:'赤字', p:'n'},
  {w:'density', m:'密度', p:'n'},
  {w:'depression', m:'萧条；抑郁', p:'n'},
  {w:'destination', m:'目的地', p:'n'},
  {w:'dilemma', m:'困境', p:'n'},
  {w:'dimension', m:'维度；尺寸', p:'n'},
  {w:'discrimination', m:'歧视', p:'n'},
  {w:'distinction', m:'区别；卓越', p:'n'},
  {w:'diversity', m:'多样性', p:'n'},
  {w:'efficiency', m:'效率', p:'n'},
  {w:'emphasis', m:'强调；重点', p:'n'},
  {w:'enterprise', m:'企业；事业心', p:'n'},
  {w:'enthusiasm', m:'热情', p:'n'},
  {w:'equality', m:'平等', p:'n'},
  {w:'estate', m:'地产', p:'n'},
  {w:'evidence', m:'证据', p:'n'},
  {w:'evolution', m:'演变；进化', p:'n'},
  {w:'exception', m:'例外', p:'n'},
  {w:'expansion', m:'扩张', p:'n'},
  {w:'expectation', m:'期望', p:'n'},
  {w:'expenditure', m:'支出', p:'n'},
  {w:'expertise', m:'专长', p:'n'},
  {w:'exposure', m:'接触；曝光', p:'n'},
  {w:'facility', m:'设施', p:'n'},
  {w:'feature', m:'特征', p:'n'},
  {w:'feedback', m:'反馈', p:'n'},
  {w:'flexibility', m:'灵活性', p:'n'},
  {w:'formula', m:'公式；方案', p:'n'},
  {w:'foundation', m:'基础；基金会', p:'n'},
  {w:'framework', m:'框架', p:'n'},
  {w:'habitat', m:'栖息地', p:'n'},
  {w:'heritage', m:'遗产', p:'n'},
  {w:'hierarchy', m:'等级制度', p:'n'},
  {w:'hypothesis', m:'假说', p:'n'},
  {w:'identity', m:'身份；特性', p:'n'},
  {w:'impact', m:'影响', p:'n'},
  {w:'incentive', m:'激励；诱因', p:'n'},
  {w:'innovation', m:'创新', p:'n'},
  {w:'insight', m:'洞察力', p:'n'},
  {w:'inspiration', m:'灵感', p:'n'},
  {w:'instinct', m:'本能', p:'n'},
  {w:'institution', m:'机构；制度', p:'n'},
  {w:'integrity', m:'正直；完整', p:'n'},
  {w:'intelligence', m:'智力；情报', p:'n'},
  {w:'interaction', m:'互动', p:'n'},
  {w:'intervention', m:'干预', p:'n'},
  {w:'investment', m:'投资', p:'n'},
  {w:'involvement', m:'参与；卷入', p:'n'},
  {w:'legislation', m:'立法；法规', p:'n'},
  {w:'likelihood', m:'可能性', p:'n'},
  {w:'limitation', m:'局限', p:'n'},
  {w:'margin', m:'边缘；利润', p:'n'},
  {w:'mechanism', m:'机制', p:'n'},
  {w:'minority', m:'少数', p:'n'},
  {w:'mode', m:'模式', p:'n'},
  {w:'motive', m:'动机', p:'n'},
  {w:'notion', m:'观念', p:'n'},
  {w:'obligation', m:'义务', p:'n'},
  {w:'occupation', m:'职业；占据', p:'n'},
  {w:'option', m:'选项', p:'n'},
  {w:'orientation', m:'方向；取向', p:'n'},
  {w:'outcome', m:'结果', p:'n'},
  {w:'participation', m:'参与', p:'n'},
  {w:'pattern', m:'模式；图案', p:'n'},
  {w:'perception', m:'认知', p:'n'},
  {w:'perspective', m:'视角', p:'n'},
  {w:'phenomenon', m:'现象', p:'n'},
  {w:'portion', m:'部分', p:'n'},
  {w:'potential', m:'潜力', p:'n'},
  {w:'prejudice', m:'偏见', p:'n'},
  {w:'principle', m:'原则', p:'n'},
  {w:'priority', m:'优先事项', p:'n'},
  {w:'procedure', m:'程序', p:'n'},
  {w:'proportion', m:'比例', p:'n'},
  {w:'prosperity', m:'繁荣', p:'n'},
  {w:'pursuit', m:'追求', p:'n'},
  {w:'qualification', m:'资格', p:'n'},
  {w:'ratio', m:'比率', p:'n'},
  {w:'reaction', m:'反应', p:'n'},
  {w:'reform', m:'改革', p:'n'},
  {w:'regulation', m:'规章', p:'n'},
  {w:'rejection', m:'拒绝', p:'n'},
  {w:'relevance', m:'相关性', p:'n'},
  {w:'relief', m:'宽慰；缓解', p:'n'},
  {w:'reputation', m:'声誉', p:'n'},
  {w:'requirement', m:'要求', p:'n'},
  {w:'reservation', m:'预订；保留', p:'n'},
  {w:'resolution', m:'决心；决议', p:'n'},
  {w:'resource', m:'资源', p:'n'},
  {w:'restriction', m:'限制', p:'n'},
  {w:'revenue', m:'收入', p:'n'},
  {w:'revolution', m:'革命；变革', p:'n'},
  {w:'scheme', m:'方案；计划', p:'n'},
  {w:'sector', m:'部门；领域', p:'n'},
  {w:'security', m:'安全', p:'n'},
  {w:'selection', m:'选择', p:'n'},
  {w:'sequence', m:'顺序', p:'n'},
  {w:'significance', m:'意义；重要性', p:'n'},
  {w:'stability', m:'稳定', p:'n'},
  {w:'standard', m:'标准', p:'n'},
  {w:'strategy', m:'策略', p:'n'},
  {w:'structure', m:'结构', p:'n'},
  {w:'supervision', m:'监督', p:'n'},
  {w:'supplement', m:'补充', p:'n'},
  {w:'survival', m:'生存', p:'n'},
  {w:'sustainability', m:'可持续性', p:'n'},
  {w:'sympathy', m:'同情', p:'n'},
  {w:'tendency', m:'倾向', p:'n'},
  {w:'tension', m:'紧张', p:'n'},
  {w:'threat', m:'威胁', p:'n'},
  {w:'tolerance', m:'容忍', p:'n'},
  {w:'transaction', m:'交易', p:'n'},
  {w:'transition', m:'过渡', p:'n'},
  {w:'treatment', m:'对待；治疗', p:'n'},
  {w:'trend', m:'趋势', p:'n'},
  {w:'utility', m:'效用', p:'n'},
  {w:'validity', m:'有效性', p:'n'},
  {w:'variety', m:'多样性；种类', p:'n'},
  {w:'vehicle', m:'车辆；载体', p:'n'},
  {w:'version', m:'版本', p:'n'},
  {w:'victim', m:'受害者', p:'n'},
  {w:'virtue', m:'美德', p:'n'},
  {w:'vision', m:'愿景；视力', p:'n'},
  {w:'vulnerability', m:'脆弱性', p:'n'},
  {w:'welfare', m:'福利', p:'n'},
  {w:'withdrawal', m:'撤回；退出', p:'n'},
  {w:'abundant', m:'丰富的', p:'a'},
  {w:'academic', m:'学术的', p:'a'},
  {w:'accessible', m:'可及的；易懂的', p:'a'},
  {w:'accurate', m:'准确的', p:'a'},
  {w:'adequate', m:'足够的', p:'a'},
  {w:'adverse', m:'不利的', p:'a'},
  {w:'aesthetic', m:'美学的', p:'a'},
  {w:'affordable', m:'负担得起的', p:'a'},
  {w:'ambiguous', m:'模糊的', p:'a'},
  {w:'ambitious', m:'有雄心的', p:'a'},
  {w:'apparent', m:'明显的', p:'a'},
  {w:'appropriate', m:'适当的', p:'a'},
  {w:'arbitrary', m:'任意的', p:'a'},
  {w:'artificial', m:'人造的', p:'a'},
  {w:'beneficial', m:'有益的', p:'a'},
  {w:'coherent', m:'连贯的', p:'a'},
  {w:'compatible', m:'兼容的', p:'a'},
  {w:'comprehensive', m:'全面的', p:'a'},
  {w:'compulsory', m:'强制的', p:'a'},
  {w:'conscious', m:'有意识的', p:'a'},
  {w:'considerable', m:'相当大的', p:'a'},
  {w:'consistent', m:'一致的', p:'a'},
  {w:'contemporary', m:'当代的', p:'a'},
  {w:'controversial', m:'有争议的', p:'a'},
  {w:'convenient', m:'方便的', p:'a'},
  {w:'conventional', m:'传统的', p:'a'},
  {w:'crucial', m:'关键的', p:'a'},
  {w:'cumulative', m:'累积的', p:'a'},
  {w:'delicate', m:'精致的；微妙的', p:'a'},
  {w:'demographic', m:'人口的', p:'a'},
  {w:'desperate', m:'绝望的；拼命的', p:'a'},
  {w:'distinct', m:'明显的；独特的', p:'a'},
  {w:'diverse', m:'多样的', p:'a'},
  {w:'dominant', m:'占主导的', p:'a'},
  {w:'drastic', m:'剧烈的', p:'a'},
  {w:'durable', m:'耐久的', p:'a'},
  {w:'dynamic', m:'动态的；有活力的', p:'a'},
  {w:'efficient', m:'高效的', p:'a'},
  {w:'elaborate', m:'精心制作的', p:'a'},
  {w:'eligible', m:'有资格的', p:'a'},
  {w:'empirical', m:'实证的', p:'a'},
  {w:'enormous', m:'巨大的', p:'a'},
  {w:'enthusiastic', m:'热情的', p:'a'},
  {w:'essential', m:'必要的；本质的', p:'a'},
  {w:'ethical', m:'道德的', p:'a'},
  {w:'excessive', m:'过度的', p:'a'},
  {w:'exclusive', m:'独有的；排他的', p:'a'},
  {w:'explicit', m:'明确的', p:'a'},
  {w:'external', m:'外部的', p:'a'},
  {w:'feasible', m:'可行的', p:'a'},
  {w:'flexible', m:'灵活的', p:'a'},
  {w:'fragile', m:'脆弱的', p:'a'},
  {w:'fundamental', m:'根本的', p:'a'},
  {w:'genuine', m:'真正的', p:'a'},
  {w:'global', m:'全球的', p:'a'},
  {w:'gradual', m:'渐进的', p:'a'},
  {w:'hostile', m:'敌对的', p:'a'},
  {w:'immense', m:'巨大的', p:'a'},
  {w:'implicit', m:'隐含的', p:'a'},
  {w:'impressive', m:'令人印象深刻的', p:'a'},
  {w:'inevitable', m:'不可避免的', p:'a'},
  {w:'inferior', m:'较差的', p:'a'},
  {w:'influential', m:'有影响力的', p:'a'},
  {w:'inherent', m:'固有的', p:'a'},
  {w:'innovative', m:'创新的', p:'a'},
  {w:'instant', m:'即时的', p:'a'},
  {w:'intensive', m:'密集的', p:'a'},
  {w:'internal', m:'内部的', p:'a'},
  {w:'intrinsic', m:'内在的', p:'a'},
  {w:'mandatory', m:'强制性的', p:'a'},
  {w:'massive', m:'大量的', p:'a'},
  {w:'mature', m:'成熟的', p:'a'},
  {w:'minimal', m:'最小的', p:'a'},
  {w:'moderate', m:'适度的', p:'a'},
  {w:'moral', m:'道德的', p:'a'},
  {w:'mutual', m:'相互的', p:'a'},
  {w:'negligible', m:'微不足道的', p:'a'},
  {w:'notorious', m:'臭名昭著的', p:'a'},
  {w:'objective', m:'客观的', p:'a'},
  {w:'obsolete', m:'过时的', p:'a'},
  {w:'obvious', m:'明显的', p:'a'},
  {w:'occasional', m:'偶尔的', p:'a'},
  {w:'optimal', m:'最优的', p:'a'},
  {w:'optional', m:'可选的', p:'a'},
  {w:'organic', m:'有机的', p:'a'},
  {w:'overall', m:'整体的', p:'a'},
  {w:'overwhelming', m:'压倒性的', p:'a'},
  {w:'permanent', m:'永久的', p:'a'},
  {w:'persistent', m:'持续的', p:'a'},
  {w:'plausible', m:'貌似合理的', p:'a'},
  {w:'portable', m:'便携的', p:'a'},
  {w:'practical', m:'实际的', p:'a'},
  {w:'precious', m:'宝贵的', p:'a'},
  {w:'preliminary', m:'初步的', p:'a'},
  {w:'prevalent', m:'普遍的', p:'a'},
  {w:'primary', m:'主要的', p:'a'},
  {w:'prior', m:'先前的', p:'a'},
  {w:'profound', m:'深刻的', p:'a'},
  {w:'prominent', m:'突出的', p:'a'},
  {w:'prospective', m:'预期的；未来的', p:'a'},
  {w:'prosperous', m:'繁荣的', p:'a'},
  {w:'psychological', m:'心理的', p:'a'},
  {w:'random', m:'随机的', p:'a'},
  {w:'rational', m:'理性的', p:'a'},
  {w:'reliable', m:'可靠的', p:'a'},
  {w:'renewable', m:'可再生的', p:'a'},
  {w:'representative', m:'有代表性的', p:'a'},
  {w:'resilient', m:'有韧性的', p:'a'},
  {w:'respective', m:'各自的', p:'a'},
  {w:'rigid', m:'僵硬的', p:'a'},
  {w:'robust', m:'强健的；稳健的', p:'a'},
  {w:'scarce', m:'稀缺的', p:'a'},
  {w:'sensible', m:'明智的', p:'a'},
  {w:'sensitive', m:'敏感的', p:'a'},
  {w:'significant', m:'重大的', p:'a'},
  {w:'simultaneous', m:'同时的', p:'a'},
  {w:'skeptical', m:'怀疑的', p:'a'},
  {w:'sophisticated', m:'复杂的；老练的', p:'a'},
  {w:'spatial', m:'空间的', p:'a'},
  {w:'specific', m:'具体的', p:'a'},
  {w:'spectacular', m:'壮观的', p:'a'},
  {w:'stable', m:'稳定的', p:'a'},
  {w:'strategic', m:'战略的', p:'a'},
  {w:'substantial', m:'大量的；实质的', p:'a'},
  {w:'subtle', m:'微妙的', p:'a'},
  {w:'sufficient', m:'充足的', p:'a'},
  {w:'supplementary', m:'补充的', p:'a'},
  {w:'sustainable', m:'可持续的', p:'a'},
  {w:'systematic', m:'系统的', p:'a'},
  {w:'tangible', m:'有形的', p:'a'},
  {w:'temporary', m:'临时的', p:'a'},
  {w:'theoretical', m:'理论的', p:'a'},
  {w:'thorough', m:'彻底的', p:'a'},
  {w:'tolerant', m:'宽容的', p:'a'},
  {w:'toxic', m:'有毒的', p:'a'},
  {w:'transparent', m:'透明的', p:'a'},
  {w:'tremendous', m:'巨大的', p:'a'},
  {w:'ultimate', m:'最终的', p:'a'},
  {w:'unanimous', m:'一致的', p:'a'},
  {w:'underlying', m:'潜在的', p:'a'},
  {w:'unprecedented', m:'前所未有的', p:'a'},
  {w:'urgent', m:'紧急的', p:'a'},
  {w:'valid', m:'有效的', p:'a'},
  {w:'verbal', m:'口头的', p:'a'},
  {w:'vertical', m:'垂直的', p:'a'},
  {w:'vital', m:'至关重要的', p:'a'},
  {w:'voluntary', m:'自愿的', p:'a'},
  {w:'widespread', m:'广泛的', p:'a'}
];

/* ================= 口语话题卡 ================= */
const TOPICS = [
  {t:'自我介绍', cn:'面试/第一节课都用得上，背熟', kw:['major in','senior student','passionate about','in my spare time'], ex:"I'm a senior majoring in Environmental Art Design. What fascinates me most is how design shapes everyday life."},
  {t:'我的专业与作品集', cn:'准备 3 个代表项目，中英文都能讲', kw:['portfolio','interior space','landscape','project concept','sustainable materials'], ex:"This project is about transforming an abandoned factory into a community space. My core idea was to preserve the industrial memory while adding modern functions."},
  {t:'AI 与设计的未来', cn:'你的差异化话题，重点准备', kw:['AI-assisted design','creative process','efficiency','human creativity','ethical concerns'], ex:"I believe AI will serve as a tool to amplify creativity rather than replace designers, allowing us to test hundreds of options in seconds."},
  {t:'可持续设计 / 环保', cn:'六级翻译和雅思常考，也是作品集亮点', kw:['eco-friendly','renewable energy','carbon footprint','green building','waste reduction'], ex:"Sustainable design is not just a trend; it's a responsibility. Even small choices, like recycled materials, can make a real difference."},
  {t:'城市更新 / 老城改造', cn:'结合城市话题，讲自己的观点', kw:['urban renewal','historic preservation','gentrification','public space','community needs'], ex:"In my view, urban renewal should respect local culture and involve residents' voices, instead of simply replacing old buildings with new ones."},
  {t:'我喜欢的城市 / 空间', cn:'准备一个具体的空间，细节越多越好', kw:['atmosphere','landmark','pedestrian street','light and shadow','street life'], ex:"My favorite place is a narrow alley in Chengdu — it's full of life, with tiny shops, hanging plants, and the smell of hotpot in the air."},
  {t:'大学时光 / 难忘经历', cn:'讲一个具体故事，含转折和感受', kw:['memorable','challenge','teamwork','turned out to be','look back on'], ex:"The most memorable experience was our graduation project. We had only two weeks left when our concept failed, but the team worked around the clock and pulled it off."},
  {t:'科技与生活', cn:'观点题：技术带来的变化', kw:['convenience','screen time','face-to-face','double-edged sword','keep up with'], ex:"Technology has made life more convenient, but it's a double-edged sword — we need to balance efficiency with real human connection."},
  {t:'我的榜样 / 灵感来源', cn:'设计师/建筑师/家人均可', kw:['role model','admire','influence','career path','guidance'], ex:"I really admire the architect Wang Shu. His way of using traditional materials in modern architecture taught me that innovation can grow from heritage."},
  {t:'未来计划 / 留学', cn:'雅思 Part 2 高频题', kw:['short-term plan','study abroad','further education','career goal','step by step'], ex:"In the next few years, I plan to study abroad to broaden my perspective, and eventually work for an international design studio."}
];

/* ================= 常用表达 ================= */
const PHRASES = [
  {cat:'衔接过渡', items:['First and foremost,… 首先最重要的一点是','In addition / Moreover,… 此外','However / On the contrary,… 然而/相反','Therefore / As a result,… 因此','Eventually / In the end,… 最终']},
  {cat:'引出观点', items:['From my perspective,… 依我看','I would argue that… 我认为（正式）','The way I see it,… 在我看来','Personally speaking,… 就我个人而言']},
  {cat:'举例说明', items:['For instance / For example,… 例如','Take … as an example 以…为例','A case in point is… 一个典型例子是','Such as … / like … 比如']},
  {cat:'加分句型', items:['What impresses me most is… 最打动我的是','It is worth noting that… 值得注意的是','Not only … but also … 不仅…而且','The reason why … is that… …的原因是','I couldn\'t agree more. 完全同意']},
  {cat:'卡壳急救', items:['Well, let me think for a second… 让我想一下','What I\'m trying to say is… 我想说的是','To put it differently,… 换个说法','In other words,… 换句话说','What I mean is… 我的意思是']},
  {cat:'设计专业词块', items:['spatial layout 空间布局','natural lighting 自然采光','human-centered design 以人为本的设计','functional zoning 功能分区','visual identity 视觉形象','green building certification 绿色建筑认证']}
];

/* ================= 资源链接导航 ================= */
const LINKS = [
  {cat:'官方信息', items:[
    {n:'四六级官网', u:'https://cet.neea.edu.cn', d:'报名、成绩、口试信息'},
    {n:'雅思中国报名', u:'https://ielts.neea.cn', d:'雅思报名与考位'},
    {n:'IELTS 官网', u:'https://www.ielts.org', d:'题型说明与免费样题'}
  ]},
  {cat:'词汇', items:[
    {n:'Anki', u:'https://apps.ankiweb.net', d:'免费记忆卡片，搜「六级核心」牌组'},
    {n:'每日英语听力', u:'https://dict.eudic.net/ting', d:'六级真题听力全套 + 精听功能'}
  ]},
  {cat:'听力', items:[
    {n:'BBC 6 Minute English', u:'https://www.bbc.co.uk/learningenglish', d:'口语跟读主力，有文本'},
    {n:'TED', u:'https://www.ted.com', d:'泛听升级材料，搜 design/architecture'}
  ]},
  {cat:'口语', items:[
    {n:'YouGlish', u:'https://youglish.com', d:'查单词在真实视频中的发音'},
    {n:'雅思口语官方样题', u:'https://www.ielts.org/for-test-takers/sample-test-questions', d:'官方口试流程演示'}
  ]},
  {cat:'雅思', items:[
    {n:'IELTS Liz', u:'https://ieltsliz.com', d:'免费题型讲解和范文'},
    {n:'IELTS Simon', u:'https://www.ielts-simon.com', d:'写作结构与观点库'}
  ]},
  {cat:'专业英文（设计）', items:[
    {n:'Dezeen', u:'https://www.dezeen.com', d:'全球设计媒体，泛读+专业词汇'},
    {n:'ArchDaily', u:'https://www.archdaily.com', d:'建筑案例英文描述'},
    {n:'Designboom', u:'https://www.designboom.com', d:'设计与科技交叉内容'}
  ]}
];
